### PR TITLE
relax version constraint on rails

### PR DESCRIPTION
**Pull request by hwhelchel**

### CODE REVIEW

**Comment by hwhelchel** [comment]
@phbernard tests still pass when bundled against Rails 6. 

You may want to relax the version constraints on your dependencies: https://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/

**Comment by hwhelchel** [comment]
@phbernard does this look good to you? would love to get a new release cut. thanks!

**Comment by phbernard** [comment]
Done! Thank you for the PR.

v0.0.13 was just published. Would you give it a try and confirm it works for you?

**Comment by hwhelchel** [comment]
Thanks @phbernard deployed cleanly. I'll let you know if I come across any issues.

**Pull request merged**
